CREATE DATABASE ConnectPlus;

USE ConnectPlus;

CREATE TABLE TipoContato(
	IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(50) NOT NULL

);

CREATE TABLE Contato(
	IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Nome NVARCHAR(100) NOT NULL,
	FormaContato VARCHAR(100),
	ImagemUrl NVARCHAR(150),
	IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);

SELECT * FROM TipoContato;
SELECT * FROM Contato;